# .jms.yml

# Allows you to filter which files are included in the review; by default, all files.
filter:

    # Patterns must match the entire path to apply; "src/" will not match "src/foo".
    paths:                ['src/Talus_Works/*'] # Example: [src/*, tests/*]
    excluded_paths:       [] # Example: [tests/*/Fixture/*]

# The default config is a base config which may be overwritten for specific paths (see below).
default_config:
    checkstyle:
        enabled:                 true
        no_trailing_whitespace:  true
        naming:
            enabled:             true
            local_variable:      ^[a-z][a-zA-Z0-9_]*$
            abstract_class_name: ^Abstract|Factory$
            utility_class_name:  Utils?$
            constant_name:       ^[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)*$
            property_name:       ^_?[a-z][a-zA-Z0-9]*$
            method_name:         ^(?:_?[a-z]|__)[a-zA-Z0-9]*$
            parameter_name:      ^[a-z][a-zA-Z0-9]*$
            interface_name:      ^[A-Z][a-zA-Z0-9]*Interface$
            type_name:           ^[A-Z][a-zA-Z0-9]*$
            exception_name:      ^[A-Z][a-zA-Z0-9]*Exception$
            isser_method_name:   ^(?:is|has|should|may|supports)

    unreachable_code:
        enabled: true

    check_access_control:
        enabled: true

    typo_checks:
        enabled: true

    suspicious_code:
        enabled:                                 true
        overriding_parameter:                    false
        overriding_closure_use:                  true
        parameter_closure_use_conflict:          true
        parameter_multiple_times:                true
        non_existent_class_in_instanceof_check:  true
        non_existent_class_in_catch_clause:      true
        assignment_of_null_return:               true
        non_commented_switch_fallthrough:        true
        non_commented_empty_catch_block:         true
        overriding_private_members:              true

    dead_assignments:
        enabled: true

    verify_php_doc_comments:
        enabled:                           false
        parameters:                        true
        return:                            true
        suggest_more_specific_types:       false
        ask_for_return_if_not_inferrable:  false
        ask_for_param_type_annotation:     false

    loops_must_use_braces:
        enabled: false

    check_usage_context:
        enabled:                    true
        method_call_on_non_object:  true
        pass_by_reference:          true
        traversable:                true
        missing_parameter:          true
        parameter_type_checks:      lenient # Allowed Values: "disabled", "lenient", "strict"

    simplify_boolean_return:
        enabled: false

    phpunit_checks:
        enabled: false

    psr0_compliance:
        enabled: false

    reflection_checks:
        enabled: true

    composer_config_check:
        enabled:        true
        publish_checks: false
        level:          warning # Allowed Values: "error", "warning"

    doc_comment_fixes:
        enabled: false

    reflection_fixes:
        enabled: false

    fabpot_cs_fixer:
        enabled: false
        level:   all # Allowed Values: "PSR-1", "PSR-2", "all"
