<?php

namespace Talus_Works\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Forum
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Forum extends EntityRepository {
}
