<?php

namespace Talus_Works\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Topic
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Topic extends EntityRepository {
}
